# Generated by Django 5.2.7 on 2025-10-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_fixer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='image',
        ),
    ]
