# Generated by Django 5.2.7 on 2025-10-24 00:18

import campus_fixer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_fixer', '0004_issue_updated_at_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issues/'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='ticket_id',
            field=models.CharField(default=campus_fixer.models.generate_ticket_id, max_length=20, unique=True),
        ),
    ]
