# Generated by Django 5.2.7 on 2025-10-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_fixer', '0005_issue_image_alter_issue_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='building',
            field=models.CharField(choices=[('academic', 'Academic Building'), ('library', 'Library'), ('hostel', 'RH Home Center'), ('cafeteria', 'Cafeteria'), ('sports', 'Gaming Room'), ('admin', 'Administrative Building')], default='academic', max_length=50),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
    ]
