# Generated by Django 5.2.7 on 2025-10-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_fixer', '0007_alter_issue_description_alter_issue_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('lost', 'Lost'), ('found', 'Found')], default='pending', max_length=20),
        ),
    ]
