# Generated by Django 5.2.6 on 2025-10-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_fixer', '0009_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
